## Introduction

Blah Blah Blah

Get dataset

In [2]:
import pandas as pd
df = pd.read_csv("games.csv")

,game_length,mmr,result,server,team_1,team_2,timestamp
0,25m 38s,NaN,Victory,na,"Riven,Nidalee,Galio,Jhin,Pantheon","Camille,Olaf,Cassiopeia,Ezreal,Alistar",2020-10-13 09:31:42
1,25m 38s,NaN,Defeat,na,"Teemo,Nidalee,Lucian,Caitlyn,Senna","Irelia,Hecarim,Cassiopeia,Jinx,Lulu",2020-10-13 06:00:17
2,25m 38s,NaN,Defeat,na,"Malphite,Olaf,Taliyah,Ezreal,Alistar","Sylas,Lillia,Lucian,Senna,Pantheon",2020-10-13 05:06:45
3,25m 38s,NaN,Defeat,na,"Neeko,Shen,Orianna,Kai'Sa,Nautilus","Riven,Hecarim,Cassiopeia,Samira,Morgana",2020-10-13 04:28:00
4,25m 38s,NaN,Defeat,na,"Fiora,Nunu & Willump,Irelia,Jhin,Karma","Renekton,Elise,Kled,Jinx,Morgana",2020-10-13 04:00:51

Some Setups

In [3]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"

%load_ext tensorboard

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "deep"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [4]:
df.head(5)

,game_length,mmr,result,server,team_1,team_2,timestamp
0,25m 38s,NaN,Victory,na,"Riven,Nidalee,Galio,Jhin,Pantheon","Camille,Olaf,Cassiopeia,Ezreal,Alistar",2020-10-13 09:31:42
1,25m 38s,NaN,Defeat,na,"Teemo,Nidalee,Lucian,Caitlyn,Senna","Irelia,Hecarim,Cassiopeia,Jinx,Lulu",2020-10-13 06:00:17
2,25m 38s,NaN,Defeat,na,"Malphite,Olaf,Taliyah,Ezreal,Alistar","Sylas,Lillia,Lucian,Senna,Pantheon",2020-10-13 05:06:45
3,25m 38s,NaN,Defeat,na,"Neeko,Shen,Orianna,Kai'Sa,Nautilus","Riven,Hecarim,Cassiopeia,Samira,Morgana",2020-10-13 04:28:00
4,25m 38s,NaN,Defeat,na,"Fiora,Nunu & Willump,Irelia,Jhin,Karma","Renekton,Elise,Kled,Jinx,Morgana",2020-10-13 04:00:51

In [46]:
temp_df = df[['game_length', 'result', 'team_1', 'team_2']] # Select only interests
blue = temp_df['team_1']
red = temp_df['team_2']
n = len(df)

blue_champs = []
red_champs = []
for i in range(0,n):
    blue_champs += [blue[i].split(',')]
    red_champs += [red[i].split(',')]
    
top = []
jg = []
mid = []
adc = []
sup = []
for i in range(0, n):
    top += [blue_champs[i][0]]
    jg += [blue_champs[i][1]]
    mid += [blue_champs[i][2]]
    adc += [blue_champs[i][3]]
    sup += [blue_champs[i][4]]
    
top_2 = []
jg_2 = []
mid_2 = []
adc_2 = []
sup_2 = []
for i in range(0, n):
    top_2 += [red_champs[i][0]]
    jg_2 += [red_champs[i][1]]
    mid_2 += [red_champs[i][2]]
    adc_2 += [red_champs[i][3]]
    sup_2 += [red_champs[i][4]]

In [52]:
data = temp_df.drop(columns=['team_1','team_2'])
# blue team
data['top1'] = top
data['jg1'] = jg
data['mid1'] = mid
data['adc1'] = adc
data['sup1'] = sup
# red team
data['top2'] = top_2
data['jg2'] = jg_2
data['mid2'] = mid_2
data['adc2'] = adc_2
data['sup2'] = sup_2

In [57]:
data.head(10)

,game_length,result,top1,jg1,mid1,adc1,sup1,top2,jg2,mid2,adc2,sup2
0,25m 38s,Victory,Riven,Nidalee,Galio,Jhin,Pantheon,Camille,Olaf,Cassiopeia,Ezreal,Alistar
1,25m 38s,Defeat,Teemo,Nidalee,Lucian,Caitlyn,Senna,Irelia,Hecarim,Cassiopeia,Jinx,Lulu
2,25m 38s,Defeat,Malphite,Olaf,Taliyah,Ezreal,Alistar,Sylas,Lillia,Lucian,Senna,Pantheon
3,25m 38s,Defeat,Neeko,Shen,Orianna,Kai'Sa,Nautilus,Riven,Hecarim,Cassiopeia,Samira,Morgana
4,25m 38s,Defeat,Fiora,Nunu & Willump,Irelia,Jhin,Karma,Renekton,Elise,Kled,Jinx,Morgana
5,25m 38s,Defeat,Irelia,Karthus,Sylas,Samira,Nautilus,Riven,Kayn,Akali,Miss Fortune,Galio
6,25m 38s,Defeat,Galio,Kindred,Syndra,Ezreal,Blitzcrank,Camille,Fiddlesticks,Twisted Fate,Jhin,Morgana
7,25m 38s,Defeat,Poppy,Ekko,Sylas,Samira,Blitzcrank,Lucian,Lillia,Lulu,Caitlyn,Alistar
8,25m 38s,Defeat,Shen,Lillia,Samira,Lucian,Soraka,Taric,Master Yi,Riven,Ezreal,Lulu
9,25m 38s,Defeat,Ornn,Graves,Sylas,Lucian,Alistar,Irelia,Hecarim,Akali,Senna,Leona

In [79]:
from sklearn.preprocessing import OneHotEncoder
#y = pd.get_dummies(data.top1, prefix='top1')
enc = OneHotEncoder()
only_champs = data.drop(columns=['game_length', 'result'])
only_champs.head(5)
only_champs_onehot = enc.fit_transform(only_champs)

In [85]:
print(only_champs_onehot)

  (0, 61)	1.0
  (0, 124)	1.0
  (0, 173)	1.0
  (0, 274)	1.0
  (0, 356)	1.0
  (0, 389)	1.0
  (0, 506)	1.0
  (0, 542)	1.0
  (0, 642)	1.0
  (0, 702)	1.0
  (1, 77)	1.0
  (1, 124)	1.0
  (1, 196)	1.0
  (1, 261)	1.0
  (1, 362)	1.0
  (1, 407)	1.0
  (1, 490)	1.0
  (1, 542)	1.0
  (1, 651)	1.0
  (1, 719)	1.0
  (2, 45)	1.0
  (2, 127)	1.0
  (2, 228)	1.0
  (2, 267)	1.0
  (2, 328)	1.0
  :	:
  (4025, 439)	1.0
  (4025, 498)	1.0
  (4025, 607)	1.0
  (4025, 637)	1.0
  (4025, 723)	1.0
  (4026, 7)	1.0
  (4026, 105)	1.0
  (4026, 214)	1.0
  (4026, 299)	1.0
  (4026, 328)	1.0
  (4026, 435)	1.0
  (4026, 489)	1.0
  (4026, 633)	1.0
  (4026, 635)	1.0
  (4026, 730)	1.0
  (4027, 80)	1.0
  (4027, 120)	1.0
  (4027, 214)	1.0
  (4027, 324)	1.0
  (4027, 363)	1.0
  (4027, 398)	1.0
  (4027, 497)	1.0
  (4027, 588)	1.0
  (4027, 642)	1.0
  (4027, 728)	1.0

In [86]:
enc.categories_

[array(['Aatrox', 'Akali', 'Anivia', 'Annie', 'Aphelios', 'Aurelion Sol',
        'Azir', 'Camille', 'Cassiopeia', "Cho'Gath", 'Corki', 'Darius',
        'Diana', 'Dr. Mundo', 'Draven', 'Ekko', 'Ezreal', 'Fiora', 'Fizz',
        'Galio', 'Gangplank', 'Garen', 'Gnar', 'Gragas', 'Graves',
        'Hecarim', 'Heimerdinger', 'Illaoi', 'Irelia', 'Janna', 'Jax',
        'Jayce', 'Jhin', 'Kalista', 'Karma', 'Kassadin', 'Katarina',
        'Kayle', 'Kayn', 'Kennen', "Kha'Zix", 'Kled', 'LeBlanc', 'Lucian',
        'Lulu', 'Malphite', 'Maokai', 'Mordekaiser', 'Neeko',
        'Nunu & Willump', 'Olaf', 'Orianna', 'Ornn', 'Pantheon', 'Poppy',
        'Pyke', 'Qiyana', 'Quinn', 'Rammus', 'Renekton', 'Rengar', 'Riven',
        'Rumble', 'Ryze', 'Samira', 'Senna', 'Sett', 'Shen', 'Singed',
        'Sion', 'Swain', 'Sylas', 'Syndra', 'Tahm Kench', 'Taliyah',
        'Talon', 'Taric', 'Teemo', 'Tristana', 'Trundle', 'Tryndamere',
        'Twisted Fate', 'Twitch', 'Udyr', 'Urgot', 'Vayne', 'Vi',
        'Vladimir', 'Volibear', 'Warwick', 'Wukong', 'Xerath', 'Yasuo',
        'Yone', 'Yorick', 'Zac', 'Zed', 'Zilean', 'Zoe'], dtype=object),
 array(['Amumu', 'Dr. Mundo', 'Ekko', 'Elise', 'Evelynn', 'Ezreal',
        'Fiddlesticks', 'Fizz', 'Galio', 'Gragas', 'Graves', 'Hecarim',
        'Ivern', 'Jarvan IV', "Kai'Sa", 'Kalista', 'Karthus', 'Kayn',
        "Kha'Zix", 'Kindred', 'Lee Sin', 'Lillia', 'Master Yi',
        'Mordekaiser', 'Morgana', 'Nidalee', 'Nocturne', 'Nunu & Willump',
        'Olaf', 'Pantheon', 'Qiyana', 'Rammus', "Rek'Sai", 'Rengar',
        'Rumble', 'Sejuani', 'Sett', 'Shaco', 'Shen', 'Shyvana', 'Singed',
        'Sion', 'Skarner', 'Sylas', 'Taliyah', 'Trundle', 'Udyr', 'Urgot',
        'Vi', 'Volibear', 'Warwick', 'Wukong', 'Xin Zhao', 'Zac'],
       dtype=object),
 array(['Aatrox', 'Ahri', 'Akali', 'Anivia', 'Annie', 'Aurelion Sol',
        'Azir', 'Camille', 'Cassiopeia', "Cho'Gath", 'Corki', 'Darius',
        'Diana', 'Dr. Mundo', 'Ekko', 'Elise', 'Ezreal', 'Fiddlesticks',
        'Fiora', 'Fizz', 'Galio', 'Garen', 'Gragas', 'Graves', 'Hecarim',
        'Heimerdinger', 'Irelia', 'Janna', 'Jax', 'Jayce', 'Jhin',
        "Kai'Sa", 'Karma', 'Karthus', 'Kassadin', 'Katarina', 'Kayle',
        'Kayn', 'Kennen', 'Kled', "Kog'Maw", 'LeBlanc', 'Lissandra',
        'Lucian', 'Lulu', 'Lux', 'Malphite', 'Malzahar', 'Maokai',
        'Master Yi', 'Mordekaiser', 'Morgana', 'Nautilus', 'Neeko',
        'Nocturne', 'Nunu & Willump', 'Orianna', 'Ornn', 'Pantheon',
        'Poppy', 'Pyke', 'Qiyana', 'Renekton', 'Riven', 'Rumble', 'Ryze',
        'Samira', 'Senna', 'Sett', 'Shen', 'Singed', 'Sion', 'Swain',
        'Sylas', 'Syndra', 'Taliyah', 'Talon', 'Taric', 'Teemo',
        'Tristana', 'Tryndamere', 'Twisted Fate', 'Urgot', 'Vayne',
        'Veigar', "Vel'Koz", 'Viktor', 'Vladimir', 'Volibear', 'Warwick',
        'Wukong', 'Xerath', 'Xin Zhao', 'Yasuo', 'Yone', 'Yuumi', 'Zac',
        'Zed', 'Ziggs', 'Zilean', 'Zoe'], dtype=object),
 array(['Ahri', 'Akali', 'Anivia', 'Aphelios', 'Ashe', 'Aurelion Sol',
        'Brand', 'Caitlyn', 'Camille', 'Cassiopeia', 'Diana', 'Draven',
        'Ekko', 'Ezreal', 'Galio', 'Graves', 'Hecarim', 'Heimerdinger',
        'Irelia', 'Jayce', 'Jhin', 'Jinx', "Kai'Sa", 'Kalista', 'Karma',
        'Karthus', 'Kassadin', 'Katarina', 'Kayle', 'Kindred', "Kog'Maw",
        'Lucian', 'Lulu', 'Lux', 'Malphite', 'Miss Fortune', 'Mordekaiser',
        'Morgana', 'Neeko', 'Nunu & Willump', 'Orianna', 'Pyke', 'Qiyana',
        'Renekton', 'Samira', 'Senna', 'Sett', 'Shen', 'Sivir', 'Sona',
        'Swain', 'Sylas', 'Syndra', 'Tahm Kench', 'Taliyah', 'Talon',
        'Tristana', 'Twitch', 'Varus', 'Vayne', 'Veigar', "Vel'Koz",
        'Vladimir', 'Volibear', 'Wukong', 'Xayah', 'Yasuo', 'Yone',
        'Yuumi', 'Zed', 'Ziggs', 'Zilean', 'Zoe'], dtype=object),
 array(['Akali', 'Alistar', 'Amumu', 'Annie', 'Aurelion Sol', 'Bard',
        'Blitzcrank', 'Brand', 'Braum', 'Camille', 'Fiddlesticks', 'Galio',
        'Gragas', 'Graves', 'Irelia', 'Janna', 'Jhin', 'Karma', 'Karthus',
        'Lee Sin', 'Leona', 'Lulu', 'Lux', 'Maokai', 'Miss Fortune',
        'Morgana', 'Nami', 'Nautilus', 'Neeko', 'Pantheon', 'Poppy',
        'Pyke', 'Rakan', 'Renekton', 'Rumble', 'Senna', 'Sett', 'Shaco',
        'Shen', 'Sion', 'Sona', 'Soraka', 'Swain', 'Syndra', 'Tahm Kench',
        'Taliyah', 'Taric', 'Teemo', 'Thresh', "Vel'Koz", 'Volibear',
        'Xerath', 'Yuumi', 'Zac', 'Zilean', 'Zoe', 'Zyra'], dtype=object),
 array(['Aatrox', 'Ahri', 'Akali', 'Annie', 'Azir', 'Camille',
        'Cassiopeia', "Cho'Gath", 'Corki', 'Darius', 'Diana', 'Dr. Mundo',
        'Ekko', 'Ezreal', 'Fiora', 'Galio', 'Gangplank', 'Garen', 'Gnar',
        'Gragas', 'Graves', 'Hecarim', 'Heimerdinger', 'Irelia', 'Janna',
        'Jax', 'Jayce', 'Jhin', "Kai'Sa", 'Kalista', 'Karma', 'Karthus',
        'Kassadin', 'Katarina', 'Kayle', 'Kennen', "Kha'Zix", 'Kled',
        'LeBlanc', 'Lillia', 'Lucian', 'Lulu', 'Malphite', 'Maokai',
        'Mordekaiser', 'Nasus', 'Nautilus', 'Neeko', 'Nunu & Willump',
        'Olaf', 'Orianna', 'Ornn', 'Pantheon', 'Poppy', 'Pyke', 'Qiyana',
        'Quinn', 'Rakan', 'Renekton', 'Rengar', 'Riven', 'Rumble', 'Ryze',
        'Samira', 'Senna', 'Sett', 'Shen', 'Singed', 'Sion', 'Swain',
        'Sylas', 'Syndra', 'Tahm Kench', 'Talon', 'Taric', 'Teemo',
        'Tristana', 'Tryndamere', 'Twisted Fate', 'Udyr', 'Urgot', 'Vayne',
        'Veigar', "Vel'Koz", 'Viktor', 'Vladimir', 'Volibear', 'Warwick',
        'Wukong', 'Yasuo', 'Yone', 'Yorick', 'Zac', 'Zed', 'Zilean', 'Zoe'],
       dtype=object),
 array(['Amumu', 'Aphelios', "Cho'Gath", 'Dr. Mundo', 'Ekko', 'Elise',
        'Evelynn', 'Fiddlesticks', 'Gragas', 'Graves', 'Hecarim', 'Ivern',
        'Jarvan IV', 'Jax', 'Karthus', 'Kayn', "Kha'Zix", 'Kindred',
        'Lee Sin', 'Lillia', 'Lux', 'Maokai', 'Master Yi', 'Nidalee',
        'Nocturne', 'Nunu & Willump', 'Olaf', 'Pantheon', 'Qiyana',
        'Rammus', "Rek'Sai", 'Rengar', 'Rumble', 'Sejuani', 'Sett',
        'Shaco', 'Shen', 'Shyvana', 'Singed', 'Skarner', 'Sylas',
        'Taliyah', 'Teemo', 'Trundle', 'Twitch', 'Udyr', 'Vi', 'Volibear',
        'Warwick', 'Xin Zhao', 'Yone', 'Zac'], dtype=object),
 array(['Aatrox', 'Ahri', 'Akali', 'Alistar', 'Anivia', 'Annie',
        'Aurelion Sol', 'Azir', 'Caitlyn', 'Camille', 'Cassiopeia',
        "Cho'Gath", 'Corki', 'Darius', 'Diana', 'Draven', 'Ekko',
        'Evelynn', 'Ezreal', 'Fiora', 'Fizz', 'Galio', 'Gangplank', 'Gnar',
        'Gragas', 'Graves', 'Heimerdinger', 'Irelia', 'Janna', 'Jarvan IV',
        'Jax', 'Jayce', 'Jhin', "Kai'Sa", 'Karma', 'Karthus', 'Kassadin',
        'Katarina', 'Kayle', 'Kayn', 'Kennen', 'Kindred', 'Kled',
        'LeBlanc', 'Lillia', 'Lissandra', 'Lucian', 'Lulu', 'Lux',
        'Malphite', 'Malzahar', 'Mordekaiser', 'Neeko', 'Nocturne',
        'Nunu & Willump', 'Olaf', 'Orianna', 'Ornn', 'Pantheon', 'Poppy',
        'Pyke', 'Qiyana', 'Rakan', 'Renekton', 'Rengar', 'Riven', 'Rumble',
        'Ryze', 'Samira', 'Sett', 'Shen', 'Singed', 'Sivir', 'Soraka',
        'Swain', 'Sylas', 'Syndra', 'Taliyah', 'Talon', 'Taric', 'Teemo',
        'Tristana', 'Tryndamere', 'Twisted Fate', 'Urgot', 'Varus',
        'Vayne', 'Veigar', "Vel'Koz", 'Viktor', 'Vladimir', 'Volibear',
        'Warwick', 'Wukong', 'Xerath', 'Xin Zhao', 'Yasuo', 'Yone', 'Zac',
        'Zed', 'Ziggs', 'Zoe'], dtype=object),
 array(['Akali', 'Aphelios', 'Ashe', 'Caitlyn', 'Camille', 'Cassiopeia',
        'Draven', 'Ekko', 'Ezreal', 'Galio', 'Garen', 'Graves',
        'Heimerdinger', 'Irelia', 'Jax', 'Jayce', 'Jhin', 'Jinx', "Kai'Sa",
        'Kalista', 'Karthus', 'Kassadin', 'Kennen', 'Kindred', "Kog'Maw",
        'Lucian', 'Lux', 'Malphite', 'Maokai', 'Master Yi', 'Miss Fortune',
        'Mordekaiser', 'Nunu & Willump', 'Orianna', 'Ornn', 'Pantheon',
        'Pyke', 'Qiyana', 'Renekton', 'Rengar', 'Rumble', 'Samira',
        'Senna', 'Sett', 'Sivir', 'Sona', 'Swain', 'Syndra', 'Taliyah',
        'Talon', 'Tristana', 'Tryndamere', 'Twisted Fate', 'Twitch',
        'Varus', 'Vayne', 'Veigar', "Vel'Koz", 'Viktor', 'Vladimir',
        'Xayah', 'Xerath', 'Yasuo', 'Yone', 'Zed', 'Ziggs', 'Zilean',
        'Zoe'], dtype=object),
 array(['Alistar', 'Bard', 'Blitzcrank', 'Brand', 'Braum', 'Camille',
        'Cassiopeia', 'Ezreal', 'Galio', 'Gragas', 'Graves', 'Ivern',
        'Janna', 'Jayce', 'Karma', 'Karthus', 'Leona', 'Lulu', 'Lux',
        'Malphite', 'Maokai', 'Morgana', 'Nami', 'Nautilus', 'Neeko',
        'Nunu & Willump', 'Pantheon', 'Poppy', 'Pyke', 'Rakan', 'Sejuani',
        'Senna', 'Sett', 'Shaco', 'Shen', 'Sion', 'Sona', 'Soraka',
        'Swain', 'Sylas', 'Tahm Kench', 'Taliyah', 'Taric', 'Thresh',
        'Trundle', "Vel'Koz", 'Xerath', 'Yasuo', 'Yuumi', 'Zac', 'Zilean',
        'Zyra'], dtype=object)]

In [98]:
except_champs = data.drop(columns=['top1','jg1','mid1','adc1','sup1','top2','jg2','mid2','adc2','sup2'])
X = [except_champs, only_champs_onehot]

Train test set

In [108]:
from sklearn.model_selection import train_test_split

# result = pd.concat(X)
# print(result)
y = X[0]['result']
print(len(y))
print(scipy.sparse.csr_matrix.getnnz(len(X[1])))
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33, random_state=42)

4028

NameError: name 'scipy' is not defined